2018-07-29 00:10:39,434 - __main__ - WARNING - Something maybe fail.
2018-07-29 00:10:39,434 - __main__ - INFO - Finish
2018-07-29 00:10:49,117 - __main__ - INFO - Start print log
2018-07-29 00:10:49,118 - __main__ - WARNING - Something maybe fail.
2018-07-29 00:10:49,118 - __main__ - INFO - Finish
2018-07-29 00:16:00,630 - __main__ - INFO - Start print log
2018-07-29 00:16:00,630 - __main__ - WARNING - Something maybe fail.
2018-07-29 00:16:00,631 - __main__ - ERROR - Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "03-get_traceback.PY", line 25, in <module>
    open("sklearn.txt","rb")
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-07-29 00:16:00,635 - __main__ - INFO - Finish
